Implement Properly Lighting OBJs and Satin Shader
0x3C50/Renderer pull request #30
Opened 2023-07-30 11:33 UTC by matthewperiut

Adds light sources (e.g. torches) affecting obj rendering, as well as time of day affecting the brightness of an object.

Attempts to match vanilla lighting on the obj rendering given it's origin pos.

Old behavior is available with the new function
```
public void draw(MatrixStack stack, Matrix4f viewMatrix, Vec3d origin, float lightLevel)
```

using this will completely restore behavior before lighting changes
```
ObjFile obj = ...;
obj.draw(stack, viewMatrix, origin, 1.f);
```

Additionally, if the obj is appended to an entity or block, it may be good to use their brightness value,
```
block.getBrightness();
entity.getBrightnessAtEyes();
```

Also adds a hook on ObjFile to add a custom shader for people who want to implement a shader on the obj model.
```
protected ShaderProgram getNormalLitShader()
```

For people who are inclined to add a custom shader use
src/resources/assets/renderer/shaders/core/obj.*
as a basis and use Satin as a tool to load core shaders to load as a ShaderProgram.

2023-07-30 11:41 UTC, 0x3C50 requested changes
overall good, but a few changes should be made

2023-07-30 11:41 UTC, 0x3C50 commented on src/main/java/me/x150/renderer/shader/ShaderManager.java
> +	public static void register() {
unnecessary method

2023-07-30 11:41 UTC, 0x3C50 commented on src/main/java/me/x150/renderer/client/RendererMain.java
> +		ShaderManager.register();
not sure if doing this here would cause issues, the context isn't made yet

2023-07-30 11:41 UTC, 0x3C50 commented on TestMod/src/main/java/me/x150/testmod/client/TestModClient.java
> +	public interface TestLocalResourceProvider extends ObjFile.ResourceProvider {
pointless extends? why not use the original ResourceProvider?

2023-07-30 11:41 UTC, 0x3C50 commented on src/main/java/me/x150/renderer/objfile/ObjFile.java
> +	 * Automatically calculates light level
should probably clarify that this only works for the origin of the model, not for the entire model

2023-07-30 12:02 UTC, matthewperiut commented on src/main/java/me/x150/renderer/objfile/ObjFile.java
> +	 * Automatically calculates light level
agreed. i'll change that.

2023-07-30 12:03 UTC, matthewperiut commented on TestMod/src/main/java/me/x150/testmod/client/TestModClient.java
> +	public interface TestLocalResourceProvider extends ObjFile.ResourceProvider {
true that, i can change that, but I'll go ahead and put a local resource provider in objfile and fix that.

2023-07-30 12:03 UTC, matthewperiut commented on src/main/java/me/x150/renderer/client/RendererMain.java
> +		ShaderManager.register();
It doesn't cause issues, code is run after an opengl context is made.

2023-07-30 12:05 UTC, matthewperiut commented on src/main/java/me/x150/renderer/shader/ShaderManager.java
> +	public static void register() {
I talked with satin devs about why the core shader was null, and turns out the ShaderManager OBJ_SHADER's .manageCoreShader needs to be run before a certain point in minecraft initialization, for some reason involving core shader initialization. Basically, if you remove the register it will crash. Basically the class needs to have the creation of the variables before core shaders are finalized, or something along these lines.

Not 100% sure of the inner-workings, am 100% sure without this the game crashes when attempting to use core shaders.

2023-07-30 12:20 UTC, matthewperiut commented on TestMod/src/main/java/me/x150/testmod/client/TestModClient.java
> +	public interface TestLocalResourceProvider extends ObjFile.ResourceProvider {
upon further inspection, I'm extending ObjFile.ResourceProvider exclusively so I can pass it into new ObjFile, and I'm not sure how to approach it otherwise.

2023-07-30 13:23 UTC, 0x3C50 commented
you can just use the original type as the return type of the method, there is no need to extend it
Am 30. Juli 2023, 14:21 +0200 schrieb Matthew Periut ***@***.***>:
> @matthewperiut commented on this pull request.
> In TestMod/src/main/java/me/x150/testmod/client/TestModClient.java:
> > +
> +                       @Override
> +                       public void reload(ResourceManager manager) {
> +                               Identifier basePath = new Identifier("testmod", "obj");
> +
> +                               ObjFile.ResourceProvider provider = TestLocalResourceProvider.ofResourceManager(manager, basePath);
> +                               try {
> +                                       testObj = new ObjFile("cubesphere.obj", (ObjFile.ResourceProvider) provider);
> +                               } catch (IOException e) {
> +                                       throw new RuntimeException(e);
> +                               }
> +                       }
> +               });
> +       }
> +
> +       public interface TestLocalResourceProvider extends ObjFile.ResourceProvider {
> upon further inspection, I'm extending ObjFile.ResourceProvider exclusively so I can pass it into new ObjFile, and I'm not sure how to approach it otherwise.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

2023-08-18 16:51 UTC, matthewperiut commented on TestMod/src/main/java/me/x150/testmod/client/TestModClient.java
> +	public interface TestLocalResourceProvider extends ObjFile.ResourceProvider {
Changed in commit [5a957aa](https://github.com/0x3C50/Renderer/pull/30/commits/5a957aae44507533a577fd33fa60ec43b4af6126)

2023-08-18 16:52 UTC, matthewperiut commented on src/main/java/me/x150/renderer/objfile/ObjFile.java
> +	 * Automatically calculates light level
Changed in commit [5a957aa](https://github.com/0x3C50/Renderer/pull/30/commits/5a957aae44507533a577fd33fa60ec43b4af6126)

2023-08-18 16:53 UTC, matthewperiut commented
Current implementation looks like this:

https://github.com/0x3C50/Renderer/assets/18296791/05894d23-deea-4a10-b840-fb95647a19ba

2023-08-18 22:59 UTC, 0x3C50 requested changes
going into the right direction, but a few changes would be nice, specifically with documentation and customization

2023-08-18 22:59 UTC, 0x3C50 commented on src/main/java/me/x150/renderer/objfile/ObjFile.java
> +	 * Automatically calculates light level at only the origin applied to the entire object.
Wording is a little weird. suggestion: `Applies correct main world lighting to the drawn object, calculated from the object's {@code origin}`

2023-08-18 22:59 UTC, 0x3C50 commented on src/main/java/me/x150/renderer/objfile/ObjFile.java
> +	 * Automatically calculates light level at only the origin applied to the entire object.
should also probably note that if no world is present, this method does nothing. maybe throw an exception instead, or let the user provide the world?

2023-08-18 22:59 UTC, 0x3C50 commented on src/main/java/me/x150/renderer/objfile/ObjFile.java
> +	 * Draws this ObjFile. Calls {@link #bake()} if necessary.
note should probably be added to indicate that this will add proper lighting to the obj

2023-08-18 22:59 UTC, 0x3C50 commented on src/main/java/me/x150/renderer/objfile/ObjFile.java
> +	 * @param lightLevel Light level to render the model at
i assume light level is 0-1? should probably add a `@Range` and Preconditions check in that case

2023-08-18 22:59 UTC, 0x3C50 commented on src/main/java/me/x150/renderer/objfile/ObjFile.java
> +	 * Draws this ObjFile. Calls {@link #bake()} if necessary.
also maybe add a note that lighting does not apply if there's no texture

2023-08-18 22:59 UTC, 0x3C50 commented on src/main/resources/assets/renderer/shaders/core/obj.fsh
> +    vec3 ambientLight = vec3(0.3, 0.3, 0.3); // You can change this value
could add as uniform and allow user to specify a custom ambient light color

2024-07-16 15:58 UTC, closed without merging